import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto,Noto_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const RobotoFont = Roboto ({
  variable : "--font-roboto",
  subsets: ["latin"],
}) 

const NotoFont = Noto_Sans ({
  variable : "--font-sans",
  subsets: ["latin"],
}) 

export const metadata: Metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${RobotoFont.variable} ${NotoFont.variable} antialiased relative`}
      >
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
